[package]
name = "yz-node"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "yz"
path = "src/main.rs"

[dependencies]
yz-proto = { path = "../yz-proto" }
yz-crypto = { path = "../yz-crypto" }
yz-rudp = { path = "../yz-rudp" }
anyhow = "1"
axum = "0.8"
clap = { version = "4", features = ["derive", "env"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
tun = { version = "0.7", features = ["async"] }
rustls = { version = "0.23", default-features = false, features = ["ring", "logging", "std", "tls12"] }
tokio-rustls = { version = "0.26", default-features = false, features = ["ring", "logging", "tls12"] }
rustls-pemfile = "2"
webpki-roots = "0.26"
log = "0.4"
env_logger = "0.11"
libc = "0.2"
